### ISSUE TITLE
Warning Thrown from Menu Registration

### ISSUE THREAD

**Issue by mikeselander** [swarminteractive/viewmedica-wordpress#17]
Hey guys, browsed through your plugin helping a mate out today and found a couple of things you might not be aware of.

`add_options_page("ViewMedica", "ViewMedica", 10, "Viewmedica-Admin", "swarm_settings");` is throwing warnings due to a bad capability being passed. The capability parameter here must be a registered WordPress capability and not an integer.

Reference: https://developer.wordpress.org/reference/functions/add_options_page/

**Comment by andrew-sipes** [comment]
80e0a1d
